SetAdvRevolt = GRN|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = GRN|$uni_GRN_Mil|40|$uni_GRN_Cav2|20|$uni_GRN_Reb|10|$uni_BSH_Rgt|4|$uni_BSH_Cav|2

SetAdvRevolt = WHI|20|20|20|10|100|NULL|NULL
SetAdvRevoltFP = WHI|$uni_WHI_Mil1|4|$uni_DON_Inf0|2|$uni_WH5_Mil0|2|$uni_WH4_Mil1|2|$uni_WHI_Cav0|1

SetAdvRevolt = WH3|20|20|20|10|100|NULL|NULL
SetAdvRevoltFP = WH3|$uni_WH3_Mil1|4|$uni_WH2_Wor|2|$uni_WH3_Cav5|1

SetAdvRevolt = RED|20|20|20|10|100|NULL|NULL
SetAdvRevoltFP = RED|$uni_RED_Mil1|3|$uni_RED_Mil6|3|$uni_RED_Cav2|3

SetAdvRevolt = ANA|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = ANA|$uni_ANA_Mil6|4|$uni_ANA_Cav1|2

SetAdvRevolt = UKR|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = UKR|$uni_UKR_Mil|4|$uni_UKR_Cav4|2

SetAdvRevolt = EST|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = EST|$uni_EST_Mil1|4|$uni_EST_Cav2|2

SetAdvRevolt = LAT|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = LAT|$uni_LAT_Mil1|4|$uni_LAT_Cav2|2

SetAdvRevolt = LIT|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = LIT|$uni_LIT_Mil1|4|$uni_LIT_Cav2|2

SetAdvRevolt = ARM|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = ARM|$uni_ARM_Mil1|4|$uni_ARM_Cav2|2

SetAdvRevolt = AZR|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = AZR|$uni_AZR_Mil1|4|$uni_AZR_Cav2|2

SetAdvRevolt = GEO|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = GEO|$uni_GEO_Mil1|4|$uni_GEO_Cav2|2

SetAdvRevolt = FIN|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = FIN|$uni_FIN_Mil5|4|$uni_FIN_Inf7|2

SetAdvRevolt = ROM|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = ROM|$uni_GRN_Mil|4|$uni_ROM_Cav2|2

SetAdvRevolt = KAZ|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = KAZ|$uni_KAZ_Mil|4|$uni_KAZ_Cav1|2

SetAdvRevolt = COS|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = COS|$uni_WHI_Rgt8|4|$uni_WHI_Cav2|2|$uni_WHI_Rgt3|4|$uni_WHI_Cav9|2|$uni_ORE_Rgt|4|$uni_ORE_Cav|2|$uni_SEM_Rgt|4|$uni_SEM_Cav|2|$uni_DON_Inf0|4|$uni_DON_Cav0|2|$uni_WH3_Rgt3|4|$uni_WH3_Cav0|2|$uni_WH3_Rgt4|4|$uni_WH3_Cav2|2|$uni_WH3_Lit0|4|$uni_WH3_Cav3|2

SetAdvRevolt = POL|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = POL|$uni_POL_Mil1|4|$uni_POL_Cav1|2