SetAdvRevolt = GRN|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = GRN|$uni_GRN_Par1|40|$uni_GRN_Par2|40|$uni_GRN_Cav0|60|$uni_BSH_Rgt|4|$uni_BSH_Cav|2

SetAdvRevolt = WHI|60|60|120|10|100|NULL|NULL
SetAdvRevoltFP = WHI|$uni_WHI_Par1|4|$uni_WHI_Par2|2

SetAdvRevolt = WH3|60|60|120|10|100|NULL|NULL
SetAdvRevoltFP = WH3|$uni_WH3_Par1|4|$uni_WH3_Par2|2|$uni_WH2_Par1|4|$uni_WH2_Par2|2

SetAdvRevolt = RED|60|60|120|10|100|NULL|NULL
SetAdvRevoltFP = RED|$uni_RED_Par1|4|$uni_RED_Par2|2

SetAdvRevolt = ANA|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = ANA|$uni_ANA_Inf1|4|$uni_ANA_Inf2|4|$uni_ANA_Cav1|2|$uni_ANA_Cav2|2

SetAdvRevolt = UKR|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = UKR|$uni_UKR_Par1|4|$uni_UKR_Par2|2

SetAdvRevolt = EST|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = EST|$uni_EST_Par1|4

SetAdvRevolt = LAT|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = LAT|$uni_LAT_Par1|4

SetAdvRevolt = LIT|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = LIT|$uni_LIT_Par1|4

SetAdvRevolt = ARM|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = ARM|$uni_ARM_Par1|4|$uni_ARM_Par2|2

SetAdvRevolt = AZR|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = AZR|$uni_AZR_Par1|4|$uni_AZR_Par2|2

SetAdvRevolt = GEO|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = GEO|$uni_GEO_Par1|4|$uni_GEO_Par2|2

SetAdvRevolt = FIN|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = FIN|$uni_FIN_Par1|4

SetAdvRevolt = ROM|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = ROM|$uni_ROM_Par1|4

SetAdvRevolt = KAZ|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = KAZ|$uni_KAZ_Par1|4|$uni_KAZ_Par2|2

SetAdvRevolt = COS|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = COS|$uni_WHI_Rgt8|4|$uni_WHI_Cav2|2|$uni_WHI_Rgt3|4|$uni_WHI_Cav9|2|$uni_ORE_Rgt|4|$uni_ORE_Cav|2|$uni_SEM_Rgt|4|$uni_SEM_Cav|2|$uni_DON_Inf0|4|$uni_DON_Cav0|2|$uni_WH3_Rgt3|4|$uni_WH3_Cav0|2|$uni_WH3_Rgt4|4|$uni_WH3_Cav2|2|$uni_WH3_Lit0|4|$uni_WH3_Cav3|2

SetAdvRevolt = POL|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = POL|$uni_POL_Par1|4