SetAdvRevolt = GRN|60|60|120|10|101|NULL|NULL
SetAdvRevoltFP = GRN|$uni_GRN_Mil|20|$uni_GRN_Par1|20|$uni_GRN_Reb|10

SetAdvRevolt = WHI|20|20|20|10|101|NULL|NULL
SetAdvRevoltFP = WHI|$uni_WHI_Par1|4

SetAdvRevolt = RED|20|20|20|10|101|NULL|NULL
SetAdvRevoltFP = RED|$uni_RED_Par1|3|$uni_RED_Par2|3|$uni_RED_Cav21|3

SetAdvRevolt = ANA|20|20|20|10|101|NULL|NULL
SetAdvRevoltFP = ANA|$uni_ANA_Par1|4|$uni_ANA_Cav2|2

