
SelectFaction = RED
  AddGarrison = -1;$sfmCity;$uni_RED_Mil6;100;x;x;x;x

SelectFaction = WHI
  AddGarrison = -1;$sfmCity;$uni_WHI_Mil1;100;x;x;x;x

SelectFaction = WH3

  AddGarrison = -1;$sfmCity;$uni_WH3_Mil1;100;x;x;x;x

SelectFaction = UKR
  AddGarrison = $Theater_Ukraine;$sfmCity;$uni_UKR_Mil;100;x;x;x;x

SelectFaction = GRN
  AddGarrison = -1;$sfmCity;$uni_GRN_Par1;100;x;x;x;x

SelectFaction = ANA
  AddGarrison = -1;$sfmCity;$uni_ANA_Inf2;100;x;x;x;x

SelectFaction = KAZ
  AddGarrison = $Theater_Central_Asia;$sfmCity;$uni_KAZ_Mil;100;x;x;x;x

SelectFaction = FIN
  AddGarrison = $Theater_Finland;$sfmCity;$uni_FIN_Mil1;100;x;x;x;x

SelectFaction = ROM
  AddGarrison = $Theater_Western;$sfmCity;$uni_ROM_Mil;100;x;x;x;x

SelectFaction = LIT
  AddGarrison = $Theater_Western;$sfmCity;$uni_LIT_Mil1;100;x;x;x;x

SelectFaction = LAT
  AddGarrison = $Theater_Western;$sfmCity;$uni_LAT_Mil1;100;x;x;x;x

SelectFaction = EST
  AddGarrison = $Theater_Western;$sfmCity;$uni_EST_Mil1;100;x;x;x;x

SelectFaction = POL
  AddGarrison = $Theater_Western;$sfmCity;$uni_POL_Mil1;100;x;x;x;x

SelectFaction = GEO
  AddGarrison = $Theater_Southern;$sfmCity;$uni_GEO_Mil1;100;x;x;x;x

SelectFaction = ARM
  AddGarrison = $Theater_Southern;$sfmCity;$uni_ARM_Mil1;100;x;x;x;x

SelectFaction = AZR
  AddGarrison = $Theater_Southern;$sfmCity;$uni_AZR_Mil1;100;x;x;x;x

SelectFaction = JAP
  AddGarrison = $Theater_Eastern;$sfmCity;$uni_WH3_Lit0;100;x;x;x;x

SelectFaction = COS
  AddGarrison = $Area_Kuban;$sfmCity;$uni_WHI_Rgt3;100;x;x;x;x
  AddGarrison = $Area_Don;$sfmCity;$uni_DON_Inf0;100;x;x;x;x
  AddGarrison = $Area_Terek;$sfmCity;$uni_WHI_Rgt8;100;x;x;x;x
  AddGarrison = $Area_Uralsk ;$sfmCity;$uni_WH3_Rgt4;100;x;x;x;x
  AddGarrison = $Area_Orenburg;$sfmCity;$uni_ORE_Rgt;100;x;x;x;x
  AddGarrison = $Area_Akmolinsk;$sfmCity;$uni_WH3_Rgt3;100;x;x;x;x
  AddGarrison = $Area_Zabaikal;$sfmCity;$uni_WH3_Lit0;100;x;x;x;x
  AddGarrison = $Area_Vladivostock;$sfmCity;$uni_WH3_Lit0;100;x;x;x;x
  AddGarrison = $Area_Semipalatinsk;$sfmCity;$uni_SEM_Rgt;100;x;x;x;x
