  NULL = NULL

SelectFaction = $RED
SelectRegion = $Petrograd

SelectRegion = $Petrograd

SelectFaction = $RED
SelectRegion = $Petrograd
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 4
  InCS = 1
  FixType = 999
  SetName = Petrograd Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Petr. Gar. Rgt|2nd Petr. Gar. Rgt|3rd Petr. Gar. Rgt
  SetName = 1st Petrograd Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 4th Petr. Gar. Rgt|5th Petr. Gar. Rgt|6th Petr. Gar. Rgt
  SetName = 2nd Petrograd Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Coa
  SUFlavorName = Coastal Fortification Bty
  SetName = Petrograd Batteries
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Petr. Bty|2nd Petr. Bty|3rd Petr. Bty|4th Petr. Bty
  SetName = Petrograd Defense
  Apply
  CreateUnit
  SetType = $uni_RED_Sup2
  SUFlavorName = 1st Co.|2nd Co.|3rd Co.|4th Co.
  SetName = Petrograd Stores
  Apply

SelectFaction = $RED
SelectRegion = $Petrograd
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 4
  InCS = 1
  FixType = 999
  SetName = Petrograd Fortress
  Apply
  CreateUnit
  SetType = $uni_RED_FtG
  SUFlavorName = Peter Battery|Pulskovo Battery
  SetName = Peter Fort
  Apply
  CreateUnit
  SetType = $uni_RED_Bal1
  SUFlavorName = Petr. Fortress Obs.Bn.
  SetName = Petr. Fortress Obs.Bn.
  Apply
  CreateUnit
  SetType = $uni_RED_Gar0
  SUFlavorName = 1st Petr. Fort. Rgt|2nd Petr. Fort. Rgt|3rd Petr. Fort. Rgt|4th Petr. Fort. Rgt
  SetName = Petrograd Fortress Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Sup2
  SUFlavorName = 1st Co.|2nd Co.|3rd Co.|4th Co.
  SetName = Peter Fort Magazine
  Apply

SelectRegion = $Moscow

SelectFaction = $RED
SelectRegion = $Moscow
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 4
  InCS = 1
  FixType = 999
  SetName = Moscow Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar0
  SUFlavorName = 1st Kremlin Gd. Rgt|2nd Kremlin Gd. Rgt|3rd Kremlin Gd.Rgt
  SetName = Kremlin Guard
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Mosk. Gar. Rgt|2nd Mosk. Gar. Rgt|3rd Mosk. Gar. Rgt
  SetName = 1st Moscow Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 4th Mosk. Gar. Rgt|5th Mosk. Gar. Rgt|6th Mosk. Gar. Rgt
  SetName = 2nd Moscow Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Mosk. Bty|2nd Mosk. Bty|3rd Mosk. Bty|4th Mosk. Bty
  SetName = Moscow Defense
  Apply
  CreateUnit
  SetType = $uni_RED_Sup2
  SUFlavorName = 1st Co.|2nd Co.|3rd Co.|4th Co.
  SetName = Moscow Stores
  Apply

SelectRegion = $Nizhniy Novgorod

SelectFaction = $RED
SelectRegion = $Nizhniy Novgorod
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Nizhniy Novgorod Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st N.Novg. Gar. Rgt|2nd N.Novg. Gar. Rgt|3rd N.Novg. Gar. Rgt
  SetName = 1st Nizhniy Novgorod Garrison
  Apply

SelectRegion = $Novgorod

SelectFaction = $RED
SelectRegion = $Novgorod
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Novgorod Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Novg. Gar. Rgt|2nd Novg. Gar. Rgt|3rd Novg. Gar. Rgt
  SetName = 1st Novgorod Garrison
  Apply

SelectRegion = $Kazan

SelectFaction = $RED
SelectRegion = $Kazan
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Kazan Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Kaz. Gar. Rgt|2nd Kaz. Gar. Rgt|3rd Kaz. Gar. Rgt
  SetName = 1st Kazan Garrison
  Apply

SelectRegion = $Tula

SelectFaction = $RED
SelectRegion = $Tula
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Tula Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Tul. Gar. Rgt|2nd Tul. Gar. Rgt|3rd Tul. Gar. Rgt
  SetName = 1st Tula Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Tul. Bty|2nd Tul. Bty|3rd Tul. Bty|4th Tul. Bty
  SetName = Tula Defense
  Apply

SelectRegion = $Samara

SelectFaction = $RED
SelectRegion = $Samara
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Samara Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Sam. Gar. Rgt|2nd Sam. Gar. Rgt|3rd Sam. Gar. Rgt
  SetName = 1st Samara Garrison
  Apply

SelectRegion = $Minsk

SelectFaction = $RED
SelectRegion = $Minsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Minsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Min. Gar. Rgt|2nd Min. Gar. Rgt|3rd Min. Gar. Rgt
  SetName = 1st Minsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Min. Bty|2nd Min. Bty|3rd Min. Bty|4th Min. Bty
  SetName = Minsk Defense
  Apply

SelectRegion = $Saratov

SelectFaction = $RED
SelectRegion = $Saratov
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Saratov Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Sar. Gar. Rgt|2nd Sar. Gar. Rgt|3rd Sar. Gar. Rgt
  SetName = 1st Saratov Garrison
  Apply

SelectRegion = $Orel

SelectFaction = $RED
SelectRegion = $Orel
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Orel Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Orl. Gar. Rgt|2nd Orl. Gar. Rgt|3rd Orl. Gar. Rgt
  SetName = 1st Orel Garrison
  Apply

SelectRegion = $Kursk

SelectFaction = $RED
SelectRegion = $Kursk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Kursk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Krsk. Gar. Rgt|2nd Krsk. Gar. Rgt|3rd Krsk. Gar. Rgt
  SetName = 1st Kursk Garrison
  Apply

SelectRegion = $Vladimir

SelectFaction = $RED
SelectRegion = $Vladimir
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Vladimir Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Vlad. Gar. Rgt|2nd Vlad. Gar. Rgt|3rd Vlad. Gar. Rgt
  SetName = 1st Vladimir Garrison
  Apply

SelectRegion = $Ryazan

SelectFaction = $RED
SelectRegion = $Ryazan
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Ryazan Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Ryz. Gar. Rgt|2nd Ryz. Gar. Rgt|3rd Ryz. Gar. Rgt
  SetName = 1st Ryazan Garrison
  Apply

SelectRegion = $Kaluga

SelectFaction = $RED
SelectRegion = $Kaluga
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Kaluga Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Kal. Gar. Rgt|2nd Kal. Gar. Rgt|3rd Kal. Gar. Rgt
  SetName = 1st Kaluga Garrison
  Apply

SelectRegion = $Bryansk

SelectFaction = $RED
SelectRegion = $Bryansk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Bryansk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Bry. Gar. Rgt|2nd Bry. Gar. Rgt|3rd Bry. Gar. Rgt
  SetName = 1st Bryansk Garrison
  Apply

SelectRegion = $Voronezh

SelectFaction = $RED
SelectRegion = $Voronezh
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Voronezh Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Vor. Gar. Rgt|2nd Vor. Gar. Rgt|3rd Vor. Gar. Rgt
  SetName = 1st Voronezh Garrison
  Apply
