  NULL = NULL

SelectFaction = $RED
SelectRegion = $Kazan

SelectRegion = $Kazan

SelectFaction = $RED
SelectRegion = $Kazan
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  FixType = 1
  SetName = Kazan Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  FlavorName = 1
  SUFlavorName = Opyt|Sobol|Gornostai|Pishtchal
  SetName = Kazan Transport Sqd
  Apply

SelectRegion = $Nizhniy Novgorod

SelectFaction = $RED
SelectRegion = $Nizhniy Novgorod
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  FixType = 1
  SetName = Nizhniy Novgorod Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Syekira|Ersh|Nerpa| Burun|
  SetName = Nizhniy Novgorod Transport Sqd
  Apply

SelectRegion = $Samara

SelectFaction = $RED
SelectRegion = $Samara
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  FixType = 1
  SetName = Samara Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Tutcha|Burya|Groza|Dojd|
  SetName = Samara Transport Sqd
  Apply

SelectRegion = $Tzaritsyn

SelectFaction = $RED
SelectRegion = $Tzaritsyn
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  FixType = 1
  SetName = Tzaritsyn Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Vikhr|Suyez|Grad|Amur|
  SetName = Tzaritsyn Transport Sqd
  Apply

SelectRegion = $Astrakhan

SelectFaction = $RED
SelectRegion = $Astrakhan
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  FixType = 1
  SetName = Astrakhan Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Yensei|Leitenant Ilin|Kapitan Saken|Kazaeski|
  SetName = Astrakhan Transport Sqd
  Apply

SelectRegion = $Yaroslavl

SelectFaction = $RED
SelectRegion = $Yaroslavl
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  FixType = 1
  SetName = Yaroslav Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Voevoda|Posadnik|Vsadnik|Gaidamak|
  SetName = Yaroslav Transport Sqd
  Apply

SelectRegion = $Kotlas

SelectFaction = $RED
SelectRegion = $Kotlas
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  FixType = 1
  SetName = Kotlas Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  NumCreate = 2
  SUFlavorName = Grinden|Abrek
  SetName = Kotlas Transport Sqd
  Apply

SelectRegion = $Voronezh

SelectFaction = $RED
SelectRegion = $Voronezh
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  FixType = 1
  SetName = Voronezh Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Chesma|Georgi Pobiedonosets|Sinop|Dvienadstat Aposotolev
  SetName = Voronezh Transport Sqd
  Apply

SelectRegion = $Perm

SelectFaction = $RED
SelectRegion = $Perm
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  FixType = 1
  SetName = Perm Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Gangut|Navarin|Tri Svititelia|Sissoli Veliki
  SetName = Perm Transport Sqd
  Apply

SelectRegion = $Bobruisk

SelectFaction = $RED
SelectRegion = $Bobruisk
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  FixType = 1
  SetName = Bobruisk Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Ushakov|Senavin|Apraksin|Petropavlovsk
  SetName = Bobruisk Transport Sqd
  Apply

SelectRegion = $Novocherkassk

SelectFaction = $RED
SelectRegion = $Novocherkassk
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  FixType = 1
  SetName = Donets Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Kommuna|Krasnoiarsk|Rurik|Pamir
  SetName = Donets Transport Sqd
  Apply

SelectRegion = $Rostov

SelectFaction = $RED
SelectRegion = $Rostov
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  FixType = 1
  SetName = Don Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Muraviev|Sorokin|Potemkine|Krasny Don
  SetName = Don Transport Sqd
  Apply

SelectRegion = $Petrograd

SelectFaction = $RED
SelectRegion = $Petrograd
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  FixType = 1
  SetName = Ladoga Transports
  Apply
  CreateUnit
  SetType = $uni_RED_RT1
  SUFlavorName = Osliabia|Pantelimon|Retvisan|Borodino|
  SetName = Ladoga Transport Sqd
  Apply

SelectRegion = $Saratov

SelectFaction = $RED
SelectRegion = $Saratov
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  FixType = 1
  SetName = Saratov Ferry
  Apply
  CreateUnit
  SetType = $uni_RED_RT2
  SUFlavorName = Saratov Barge 01|Saratov Barge 02t|Saratov Barge 03|Saratov Barge 04
  SetName = Saratov Ferry
  Apply

SelectRegion = $Syzran

SelectFaction = $RED
SelectRegion = $Syzran
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  FixType = 1
  SetName = Syzran Ferry
  Apply
  CreateUnit
  SetType = $uni_RED_RT2
  SUFlavorName = Syzran Barge 01|Syzran Barge 02t|Syzran Barge 03|Syzran Barge 04
  SetName = Syzran Ferry
  Apply

SelectRegion = $Cheboksary

SelectFaction = $RED
SelectRegion = $Cheboksary
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  FixType = 1
  SetName = Cheboksary Ferry
  Apply
  CreateUnit
  SetType = $uni_RED_RT2
  SUFlavorName = Cheboksary Barge 01|Cheboksary Barge 02t|Cheboksary Barge 03|Cheboksary Barge 04
  SetName = Cheboksary Ferry
  Apply

SelectRegion = $Kostroma

SelectFaction = $RED
SelectRegion = $Kostroma
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  FixType = 1
  SetName = Kostroma Ferry
  Apply
  CreateUnit
  SetType = $uni_RED_RT2
  SUFlavorName = Kostroma Barge 01|Kostroma Barge 02t|Kostroma Barge 03|Kostroma Barge 04
  SetName = Kostroma Ferry
  Apply

SelectRegion = $Rybinsk

SelectFaction = $RED
SelectRegion = $Rybinsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  FixType = 1
  SetName = Rybinsk Ferry
  Apply
  CreateUnit
  SetType = $uni_RED_RT2
  SUFlavorName = Rybinsk Barge 01|Rybinsk Barge 02t|Rybinsk Barge 03|Rybinsk Barge 04
  SetName = Rybinsk Ferry
  Apply

SelectRegion = $Novgorod

SelectFaction = $RED
SelectRegion = $Novgorod
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  FixType = 1
  SetName = Novgorod Ferry
  Apply
  CreateUnit
  SetType = $uni_RED_RT2
  SUFlavorName = Novgorod Barge 01|Novgorod Barge 02t|Novgorod Barge 03|Novgorod Barge 04
  SetName = Novgorod Ferry
  Apply

SelectRegion = $Petrozavodsk

SelectFaction = $RED
SelectRegion = $Petrozavodsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Nav
  Entranch = 0
  FixType = 1
  SetName = Petrozavodsk Ferry
  Apply
  CreateUnit
  SetType = $uni_RED_RT2
  SUFlavorName = Petrozavodsk Barge 01|Petrozavodsk Barge 02t|Petrozavodsk Barge 03|Petrozavodsk Barge 04
  SetName = Petrozavodsk Ferry
  Apply
