
SelectFaction = $RED
  AddGarrison = $Theater_Northern;$sfmDepot;$uni_RED_Gar1;100;x;x;x;x
  AddGarrison = $Theater_Western;$sfmDepot;$uni_RED_Gar1;100;x;x;x;x
  AddGarrison = $Theater_Finland;$sfmDepot;$uni_RED_Gar1;100;x;x;x;x
  AddGarrison = $Theater_Belarus;$sfmDepot;$uni_RED_Gar1;100;x;x;x;x
  AddGarrison = $Theater_Central_Russia;$sfmDepot;$uni_RED_Rgt6;100;x;x;x;x
  AddGarrison = $Theater_Ukraine;$sfmDepot;$uni_RED_Gar1;100;x;x;x;x
  AddGarrison = $Theater_Southern;$sfmDepot;$uni_RED_Gar1;100;x;x;x;x
  AddGarrison = $Theater_Ural;$sfmDepot;$uni_RED_Gar1;100;x;x;x;x
  AddGarrison = $Theater_Volga;$sfmDepot;$uni_RED_Gar1;100;x;x;x;x
  AddGarrison = $Theater_Siberia;$sfmDepot;$uni_RED_Gar1;100;x;x;x;x

SelectFaction = $GER
  AddGarrison = $Theater_Finland;$sfmDepot;$uni_FIN_MilAG;100;x;x;x;x
  AddGarrison = $Theater_Western;$sfmDepot;$uni_GER_Gar2;100;x;x;x;x
  AddGarrison = $Theater_Central_Russia;$sfmDepot;$uni_GER_Gar2;100;x;x;x;x
  AddGarrison = $Theater_Southern;$sfmDepot;$uni_DON_MilAG;100;x;x;x;x
  AddGarrison = $Theater_Ukraine;$sfmDepot;$uni_UKR_MilAG;100;x;x;x;x

SelectFaction = $WHI
  AddGarrison = $Theater_Central_Russia;$sfmDepot;$uni_WHI_MilAG;100;x;x;x;x
  AddGarrison = $Theater_Belarus;$sfmDepot;$uni_WHI_MilAG;100;x;x;x;x
  AddGarrison = $Theater_Ukraine;$sfmDepot;$uni_WHI_MilAG;100;x;x;x;x

SelectFaction = $GRN
  AddGarrison = -1;$sfmDepot;$uni_GRN_MilAG;100;x;x;x;x

SelectFaction = $ANA
  AddGarrison = -1;$sfmDepot;$uni_ANA_Par1;100;x;x;x;x

SelectFaction = $RED
  AddGarrison = $Theater_Northern;$sfmRedoubt;$uni_RED_Gar2;100;x;x;x;x
  AddGarrison = $Theater_Western;$sfmRedoubt;$uni_RED_Gar2;100;x;x;x;x
  AddGarrison = $Theater_Finland;$sfmRedoubt;$uni_RED_Gar2;100;x;x;x;x
  AddGarrison = $Theater_Belarus;$sfmRedoubt;$uni_RED_Gar2;100;x;x;x;x
  AddGarrison = $Theater_Central_Russia;$sfmRedoubt;$uni_RED_Gar2;100;x;x;x;x
  AddGarrison = $Theater_Ukraine;$sfmRedoubt;$uni_RED_Gar2;100;x;x;x;x
  AddGarrison = $Theater_Southern;$sfmRedoubt;$uni_RED_Gar2;100;x;x;x;x
  AddGarrison = $Theater_Ural;$sfmRedoubt;$uni_RED_Gar2;100;x;x;x;x
  AddGarrison = $Theater_Volga;$sfmRedoubt;$uni_RED_Gar2;100;x;x;x;x

SelectFaction = $GER
  AddGarrison = $Theater_Finland;$sfmRedoubt;$uni_FIN_MilAG;100;x;x;x;x
  AddGarrison = $Theater_Western;$sfmRedoubt;$uni_GER_Gar2;100;x;x;x;x
  AddGarrison = $Theater_Central_Russia;$sfmRedoubt;$uni_GER_Gar2;100;x;x;x;x
  AddGarrison = $Theater_Southern;$sfmRedoubt;$uni_DON_MilAG;100;x;x;x;x
  AddGarrison = $Theater_Ukraine;$sfmRedoubt;$uni_UKR_MilAG;100;x;x;x;x

SelectFaction = $WHI
  AddGarrison = $Theater_Central_Russia;$sfmRedoubt;$uni_WHI_MilAG;100;x;x;x;x
  AddGarrison = $Theater_Belarus;$sfmRedoubt;$uni_WHI_MilAG;100;x;x;x;x
  AddGarrison = $Theater_Ukraine;$sfmRedoubt;$uni_WHI_MilAG;100;x;x;x;x

SelectFaction = $GRN
  AddGarrison = -1;$sfmRedoubt;$uni_GRN_MilAG;100;x;x;x;x

SelectFaction = $ANA
  AddGarrison = -1;$sfmRedoubt;$uni_ANA_Par1;100;x;x;x;x

SelectFaction = $RED
  AddGarrison = $Theater_Northern;$sfmCity;$uni_RED_MilAG;50;x;x;x;x
  AddGarrison = $Theater_Western;$sfmCity;$uni_RED_MilAG;50;x;x;x;x
  AddGarrison = $Theater_Finland;$sfmCity;$uni_RED_MilAG;50;x;x;x;x
  AddGarrison = $Theater_Belarus;$sfmCity;$uni_RED_MilAG;50;x;x;x;x
  AddGarrison = $Theater_Central_Russia;$sfmCity;$uni_RED_MilAG;50;x;x;x;x
  AddGarrison = $Theater_Ukraine;$sfmCity;$uni_RED_MilAG;50;x;x;x;x
  AddGarrison = $Theater_Southern;$sfmCity;$uni_RED_MilAG;50;x;x;x;x
  AddGarrison = $Theater_Ural;$sfmCity;$uni_RED_MilAG;50;x;x;x;x
  AddGarrison = $Theater_Volga;$sfmCity;$uni_RED_MilAG;50;x;x;x;x

SelectFaction = $GER
  AddGarrison = $Theater_Finland;$sfmCity;$uni_FIN_MilAG;50;x;x;x;x
  AddGarrison = $Theater_Western;$sfmCity;$uni_GER_Gar2;50;x;x;x;x
  AddGarrison = $Theater_Central_Russia;$sfmCity;$uni_GER_Gar2;50;x;x;x;x
  AddGarrison = $Theater_Southern;$sfmCity;$uni_DON_MilAG;50;x;x;x;x
  AddGarrison = $Theater_Ukraine;$sfmCity;$uni_WHI_MilAG;50;x;x;x;x

SelectFaction = $WHI
  AddGarrison = $Theater_Central_Russia;$sfmCity;$uni_UKR_MilAG;50;x;x;x;x
  AddGarrison = $Theater_Belarus;$sfmCity;$uni_WHI_MilAG;50;x;x;x;x
  AddGarrison = $Theater_Ukraine;$sfmCity;$uni_WHI_MilAG;50;x;x;x;x

SelectFaction = $GRN
  AddGarrison = -1;$sfmCity;$uni_GRN_MilAG;50;x;x;x;x

SelectFaction = $ANA
  AddGarrison = -1;$sfmCity;$uni_ANA_Par1;50;x;x;x;x

SelectFaction = $RED
  AddGarrison = $Theater_Northern;$sfmFort;$uni_RED_Gar3;100;x;x;x;x
  AddGarrison = $Theater_Western;$sfmFort;$uni_RED_Gar3;100;x;x;x;x
  AddGarrison = $Theater_Finland;$sfmFort;$uni_RED_Gar3;100;x;x;x;x
  AddGarrison = $Theater_Belarus;$sfmFort;$uni_RED_Gar3;100;x;x;x;x
  AddGarrison = $Theater_Central_Russia;$sfmFort;$uni_RED_Gar3;100;x;x;x;x
  AddGarrison = $Theater_Ukraine;$sfmFort;$uni_RED_Gar3;100;x;x;x;x
  AddGarrison = $Theater_Southern;$sfmFort;$uni_RED_Gar3;100;x;x;x;x
  AddGarrison = $Theater_Ural;$sfmFort;$uni_RED_Gar3;100;x;x;x;x
  AddGarrison = $Theater_Volga;$sfmFort;$uni_RED_Gar3;100;x;x;x;x

SelectFaction = $GER
  AddGarrison = $Theater_Finland;$sfmFort;$uni_FIN_MilAG;100;x;x;x;x
  AddGarrison = $Theater_Western;$sfmFort;$uni_GER_Gar2;100;x;x;x;x
  AddGarrison = $Theater_Central_Russia;$sfmFort;$uni_GER_Gar2;100;x;x;x;x
  AddGarrison = $Theater_Southern;$sfmFort;$uni_DON_MilAG;100;x;x;x;x
  AddGarrison = $Theater_Ukraine;$sfmFort;$uni_UKR_MilAG;100;x;x;x;x

SelectFaction = $WHI
  AddGarrison = $Theater_Central_Russia;$sfmFort;$uni_WHI_MilAG;100;x;x;x;x
  AddGarrison = $Theater_Belarus;$sfmFort;$uni_WHI_MilAG;100;x;x;x;x
  AddGarrison = $Theater_Ukraine;$sfmFort;$uni_WHI_MilAG;100;x;x;x;x

SelectFaction = $GRN
  AddGarrison = -1;$sfmFort;$uni_GRN_MilAG;100;x;x;x;x

SelectFaction = $ANA
  AddGarrison = -1;$sfmFort;$uni_ANA_Par1;100;x;x;x;x

SelectFaction = $RED
  AddGarrison = $Theater_Northern;$sfmHarbor;$uni_RED_Gar2;20;x;x;x;x
  AddGarrison = $Theater_Western;$sfmHarbor;$uni_RED_Gar2;20;x;x;x;x
  AddGarrison = $Theater_Finland;$sfmHarbor;$uni_RED_Gar2;20;x;x;x;x
  AddGarrison = $Theater_Belarus;$sfmHarbor;$uni_RED_Gar2;20;x;x;x;x
  AddGarrison = $Theater_Central_Russia;$sfmHarbor;$uni_RED_Gar2;20;x;x;x;x
  AddGarrison = $Theater_Ukraine;$sfmHarbor;$uni_RED_Gar2;20;x;x;x;x
  AddGarrison = $Theater_Southern;$sfmHarbor;$uni_RED_Gar2;20;x;x;x;x
  AddGarrison = $Theater_Ural;$sfmHarbor;$uni_RED_Gar2;20;x;x;x;x
  AddGarrison = $Theater_Volga;$sfmHarbor;$uni_RED_Gar2;20;x;x;x;x

SelectFaction = $GER
  AddGarrison = $Theater_Finland;$sfmHarbor;$uni_FIN_MilAG;20;x;x;x;x
  AddGarrison = $Theater_Western;$sfmHarbor;$uni_GER_Gar2;20;x;x;x;x
  AddGarrison = $Theater_Central_Russia;$sfmHarbor;$uni_GER_Gar2;20;x;x;x;x
  AddGarrison = $Theater_Southern;$sfmHarbor;$uni_DON_MilAG;20;x;x;x;x
  AddGarrison = $Theater_Ukraine;$sfmHarbor;$uni_UKR_MilAG;20;x;x;x;x

SelectFaction = $WHI
  AddGarrison = $Theater_Central_Russia;$sfmHarbor;$uni_WHI_MilAG;20;x;x;x;x
  AddGarrison = $Theater_Belarus;$sfmHarbor;$uni_WHI_MilAG;20;x;x;x;x
  AddGarrison = $Theater_Ukraine;$sfmHarbor;$uni_WHI_MilAG;20;x;x;x;x

SelectFaction = $GRN
  AddGarrison = -1;$sfmHarbor;$uni_GRN_MilAG;20;x;x;x;x

SelectFaction = $ANA
  AddGarrison = -1;$sfmHarbor;$uni_ANA_Par1;20;x;x;x;x
