  NULL = NULL

SelectFaction = $RED
SelectRegion = $Petrograd

SelectRegion = $Petrograd

SelectFaction = $RED
SelectRegion = $Petrograd
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 8
  InCS = 1
  FixType = 999
  SetName = Petrograd Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Petr. Gar. Rgt|2nd Petr. Gar. Rgt|3rd Petr. Gar. Rgt
  SetLevel = 1
  SetName = 1st Petrograd Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 4th Petr. Gar. Rgt|5th Petr. Gar. Rgt|6th Petr. Gar. Rgt
  SetName = 2nd Petrograd Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_VOKhR2
  SUFlavorName = 1st Petr. VOKhR Rgt|2nd Petr. VOKhR Rgt|3rd Petr. VOKhR Rgt|VOKhR Petr. Bty
  SetName = Petrograd VOKhR Bde
  Apply
  CreateUnit
  SetType = $uni_RED_Coa
  SUFlavorName = Coastal Fortification Bty
  SetName = Petr. North Batteries
  Apply
  CreateUnit
  SetType = $uni_RED_Coa
  SUFlavorName = Coastal Fortification Bty
  SetName = Petr. South Batteries
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Petr. Bty|2nd Petr. Bty|3rd Petr. Bty|4th Petr. Bty
  SetName = Petrograd Defense
  Apply
  CreateUnit
  SetType = $uni_RED_Sup2
  SetName = Petrograd Stores
  Apply

SelectFaction = $RED
SelectRegion = $Petrograd
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 4
  InCS = 1
  FixType = 999
  SetName = Petrograd Fortress
  Apply
  CreateUnit
  SetType = $uni_RED_FtG
  SUFlavorName = Peter Battery|Pulskovo Battery
  SetLevel = 1
  SetName = Peter Fort
  Apply
  CreateUnit
  SetType = $uni_RED_Bal1
  SUFlavorName = Petr. Fortress Obs.Bn.
  SetLevel = 1
  SetName = Petr. Fortress Obs.Bn.
  Apply
  CreateUnit
  SetType = $uni_RED_Gar0
  SUFlavorName = 1st Petr. Fort. Rgt|2nd Petr. Fort. Rgt|3rd Petr. Fort. Rgt|4th Petr. Fort. Rgt
  SetLevel = 1
  SetName = Petrograd Fortress Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Sup2
  SUFlavorName = 1st Co.|2nd Co.|3rd Co.|4th Co.
  SetLevel = 1
  SetName = Peter Fort Magazine
  Apply

SelectRegion = $Moscow

SelectFaction = $RED
SelectRegion = $Moscow
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 4
  InCS = 1
  FixType = 999
  SetName = Moscow Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar0
  SUFlavorName = 1st Kremlin Gd. Rgt|2nd Kremlin Gd. Rgt|3rd Kremlin Gd.Rgt
  SetLevel = 2
  SetName = Kremlin Guard
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Mosk. Gar. Rgt|2nd Mosk. Gar. Rgt|3rd Mosk. Gar. Rgt
  SetName = 1st Moscow Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 4th Mosk. Gar. Rgt|5th Mosk. Gar. Rgt|6th Mosk. Gar. Rgt
  SetName = 2nd Moscow Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_VOKhR2
  SUFlavorName = 1st Mosk. VOKhR Rgt|2nd Mosk. VOKhR Rgt|3rd Mosk. VOKhR Rgt|VOKhR Mosk. Bty
  SetName = Moscow VOKhR Bde
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Mosk. Bty|2nd Mosk. Bty|3rd Mosk. Bty|4th Mosk. Bty
  SetName = Moscow Defense
  Apply
  CreateUnit
  SetType = $uni_RED_Sup2
  SetName = Moscow Stores
  Apply

SelectRegion = $Nizhniy Novgorod

SelectFaction = $RED
SelectRegion = $Nizhniy Novgorod
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Nizhniy Novgorod Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Tck
  SUFlavorName = Nij-Novgorod Cheka
  SetName = Nij-Novgorod Cheka
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st N.Novg. Gar. Rgt|2nd N.Novg. Gar. Rgt|3rd N.Novg. Gar. Rgt
  SetName = 1st Nizhniy Novgorod Garrison
  Apply

SelectRegion = $Novgorod

SelectFaction = $RED
SelectRegion = $Novgorod
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Novgorod Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Novg. Gar. Rgt|2nd Novg. Gar. Rgt|3rd Novg. Gar. Rgt
  SetName = 1st Novgorod Garrison
  Apply

SelectRegion = $Kazan

SelectFaction = $RED
SelectRegion = $Kazan
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Kazan Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Kaz. Gar. Rgt|2nd Kaz. Gar. Rgt|3rd Kaz. Gar. Rgt
  SetName = 1st Kazan Garrison
  Apply

SelectRegion = $Tula

SelectFaction = $RED
SelectRegion = $Tula
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Tula Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Tck
  SUFlavorName = Tula Cheka
  SetName = Tula Cheka
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Tul. Gar. Rgt|2nd Tul. Gar. Rgt|3rd Tul. Gar. Rgt
  SetName = 1st Tula Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Tul. Bty|2nd Tul. Bty|3rd Tul. Bty|4th Tul. Bty
  SetName = Tula Defense
  Apply

SelectRegion = $Samara

SelectFaction = $RED
SelectRegion = $Samara
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Samara Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Tck
  SUFlavorName = Samara Cheka
  SetName = Samara Cheka
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Sam. Gar. Rgt|2nd Sam. Gar. Rgt|3rd Sam. Gar. Rgt
  SetName = 1st Samara Garrison
  Apply

SelectRegion = $Minsk

SelectFaction = $RED
SelectRegion = $Minsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Minsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Tck
  SUFlavorName = Minsk Cheka
  SetName = Minsk Cheka
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Min. Gar. Rgt|2nd Min. Gar. Rgt|3rd Min. Gar. Rgt
  SetName = 1st Minsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Min. Bty|2nd Min. Bty|3rd Min. Bty|4th Min. Bty
  SetName = Minsk Defense
  Apply

SelectRegion = $Saratov

SelectFaction = $RED
SelectRegion = $Saratov
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Saratov Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Sar. Gar. Rgt|2nd Sar. Gar. Rgt|3rd Sar. Gar. Rgt
  SetName = 1st Saratov Garrison
  Apply

SelectRegion = $Orel

SelectFaction = $RED
SelectRegion = $Orel
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Orel Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Orl. Gar. Rgt|2nd Orl. Gar. Rgt|3rd Orl. Gar. Rgt
  SetName = 1st Orel Garrison
  Apply

SelectRegion = $Kursk

SelectFaction = $RED
SelectRegion = $Kursk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Kursk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Krsk. Gar. Rgt|2nd Krsk. Gar. Rgt|3rd Krsk. Gar. Rgt
  SetName = 1st Kursk Garrison
  Apply

SelectRegion = $Vladimir

SelectFaction = $RED
SelectRegion = $Vladimir
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Vladimir Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Vlad. Gar. Rgt|2nd Vlad. Gar. Rgt|3rd Vlad. Gar. Rgt
  SetName = 1st Vladimir Garrison
  Apply

SelectRegion = $Ryazan

SelectFaction = $RED
SelectRegion = $Ryazan
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Ryazan Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Ryz. Gar. Rgt|2nd Ryz. Gar. Rgt|3rd Ryz. Gar. Rgt
  SetName = 1st Ryazan Garrison
  Apply

SelectRegion = $Kaluga

SelectFaction = $RED
SelectRegion = $Kaluga
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Kaluga Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Kal. Gar. Rgt|2nd Kal. Gar. Rgt|3rd Kal. Gar. Rgt
  SetName = 1st Kaluga Garrison
  Apply

SelectRegion = $Bryansk

SelectFaction = $RED
SelectRegion = $Bryansk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Bryansk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Bry. Gar. Rgt|2nd Bry. Gar. Rgt|3rd Bry. Gar. Rgt
  SetName = 1st Bryansk Garrison
  Apply

SelectRegion = $Voronezh

SelectFaction = $RED
SelectRegion = $Voronezh
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Voronezh Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Vor. Gar. Rgt|2nd Vor. Gar. Rgt|3rd Vor. Gar. Rgt
  SetName = 1st Voronezh Garrison
  Apply

SelectRegion = $Smolensk

SelectFaction = $RED
SelectRegion = $Smolensk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 4
  InCS = 1
  FixType = 999
  SetName = Smolensk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Tck
  SUFlavorName = Smolensk Cheka
  SetName = Smolensk Cheka
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Smo. Gar. Rgt|2nd Smo. Gar. Rgt|3rd Smo. Gar. Rgt
  SetName = 1st Smolensk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Smo. Bty|2nd Smo. Bty|3rd Smo. Bty|4th Smo. Bty
  SetName = Smolensk Defense
  Apply
  CreateUnit
  SetType = $uni_RED_Sup2
  SetName = Smolensk Stores
  Apply

SelectRegion = $Chernigov

SelectFaction = $RED
SelectRegion = $Chernigov
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 4
  InCS = 1
  FixType = 999
  SetName = Chernigov Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Cher. Gar. Rgt|2nd Cher. Gar. Rgt|3rd Cher. Gar. Rgt
  SetName = 1st Chernigov Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Cher. Bty|2nd Cher. Bty|3rd Cher. Bty|4th Cher. Bty
  SetName = Chernigov Defense
  Apply

SelectRegion = $Yaroslavl

SelectFaction = $RED
SelectRegion = $Yaroslavl
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Yaroslav Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Yar. Gar. Rgt|2nd Yar. Gar. Rgt|3rd Yar. Gar. Rgt
  SetName = 1st Yaroslav Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Yar. Bty|2nd Yar. Bty|3rd Yar. Bty|4th Yar. Bty
  SetName = Yaroslav Defense
  Apply

SelectRegion = $Ivanovo

SelectFaction = $RED
SelectRegion = $Ivanovo
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Ivanovo Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Ivan. Gar. Rgt|2nd Ivan. Gar. Rgt|3rd Ivan. Gar. Rgt
  SetName = 1st Ivanovo Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Ivan. Bty|2nd Ivan. Bty|3rd Ivan. Bty|4th Ivan. Bty
  SetName = Ivanovo Defense
  Apply

SelectRegion = $Rostov

SelectFaction = $RED
SelectRegion = $Rostov
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Rostov Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Tck
  SUFlavorName = Rostov Cheka
  SetName = Rostov Cheka
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Ros. Gar. Rgt|2nd Ros. Gar. Rgt|3rd Ros. Gar. Rgt
  SetName = 1st Rostov Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Ros. Bty|2nd Ros. Bty|3rd Ros. Bty|4th Ros. Bty
  SetName = Rostov Defense
  Apply

SelectRegion = $Tzaritsyn

SelectFaction = $RED
SelectRegion = $Tzaritsyn
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 4
  InCS = 1
  FixType = 999
  SetName = Tzaritsyn Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Tck
  SUFlavorName = Tzaritsyn Cheka
  SetName = Tzaritsyn Cheka
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Tza. Gar. Rgt|2nd Tza. Gar. Rgt|3rd Tza. Gar. Rgt
  SetName = 1st Tzaritsyn Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Tza. Bty|2nd Tza. Bty|3rd Tza. Bty|4th Tza. Bty
  SetName = Tzaritsyn Defense
  Apply
  CreateUnit
  SetType = $uni_RED_Sup2
  SetName = Tzaritsyn Stores
  Apply

SelectRegion = $Astrakhan

SelectFaction = $RED
SelectRegion = $Astrakhan
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Astrakhan Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Ast. Gar. Rgt|2nd Ast. Gar. Rgt|3rd Ast. Gar. Rgt
  SetName = 1st Astrakhan Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Ast. Bty|2nd Ast. Bty|3rd Ast. Bty|4th Ast. Bty
  SetName = Astrakhan Defense
  Apply

SelectRegion = $Orenburg

SelectFaction = $RED
SelectRegion = $Orenburg
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Orenburg Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Ore. Gar. Rgt|2nd Ore. Gar. Rgt|3rd Ore. Gar. Rgt
  SetName = 1st Orenburg Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Ore. Bty|2nd Ore. Bty|3rd Ore. Bty|4th Ore. Bty
  SetName = Orenburg Defense
  Apply

SelectRegion = $Perm

SelectFaction = $RED
SelectRegion = $Perm
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Perm Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Per. Gar. Rgt|2nd Per. Gar. Rgt|3rd Per. Gar. Rgt
  SetName = 1st Perm Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Per. Bty|2nd Per. Bty|3rd Per. Bty|4th Per. Bty
  SetName = Perm Defense
  Apply

SelectRegion = $Vladikavkaz

SelectFaction = $RED
SelectRegion = $Vladikavkaz
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 4
  InCS = 1
  FixType = 999
  SetName = Vladikavkaz Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Vla. Gar. Rgt|2nd Vla. Gar. Rgt|3rd Vla. Gar. Rgt
  SetName = 1st Vladikavkaz Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Vla. Bty|2nd Vla. Bty|3rd Vla. Bty|4th Vla. Bty
  SetName = Vladikavkaz Defense
  Apply

SelectRegion = $Ekaterinburg

SelectFaction = $RED
SelectRegion = $Ekaterinburg
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Ekaterinburg Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Tck
  SUFlavorName = Ekaterinburg Cheka
  SetName = Ekaterinburg Cheka
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Eka. Gar. Rgt|2nd Eka. Gar. Rgt|3rd Eka. Gar. Rgt
  SetName = 1st Ekaterinburg Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Eka. Bty|2nd Eka. Bty|3rd Eka. Bty|4th Eka. Bty
  SetName = Ekaterinburg Defense
  Apply

SelectRegion = $Murmansk

SelectFaction = $RED
SelectRegion = $Murmansk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 4
  InCS = 1
  FixType = 999
  SetName = Murmansk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Murm. Gar. Rgt|2nd Murm. Gar. Rgt|3rd Murm. Gar. Rgt
  SetName = Murmansk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Coa
  SUFlavorName = Coastal Fortification Bty
  SetName = Murmansk Batteries
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Murm. Bty|2nd Murm. Bty|3rd Murm. Bty|4th Murm. Bty
  SetName = Murmansk Defense
  Apply

SelectRegion = $Arkhangelsk

SelectFaction = $RED
SelectRegion = $Arkhangelsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 4
  InCS = 1
  FixType = 999
  SetName = Arkhangelsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Ark. Gar. Rgt|2nd Ark. Gar. Rgt|3rd Ark. Gar. Rgt
  SetName = Arkhangelsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Coa
  SUFlavorName = Coastal Fortification Bty
  SetName = Arkhangelsk Batteries
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Ark. Bty|2nd Ark. Bty|3rd Ark. Bty|4th Ark. Bty
  SetName = Arkhangelsk Defense
  Apply

SelectRegion = $Piatigorsk

SelectFaction = $RED
SelectRegion = $Piatigorsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Piatigorsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Pia. Gar. Rgt|2nd Pia. Gar. Rgt|3rd Pia. Gar. Rgt
  SetName = 1st Piatigorsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Pia. Bty|2nd Pia. Bty|3rd Pia. Bty|4th Pia. Bty
  SetName = Piatigorsk Defense
  Apply

SelectRegion = $Olonets

SelectFaction = $RED
SelectRegion = $Olonets
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Olonets Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Oln. Gar. Rgt|2nd Oln. Gar. Rgt|3rd Oln. Gar. Rgt
  SetName = 1st Olonets Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Olo. Bty|2nd Olo. Bty|3rd Olo. Bty|4th Olo. Bty
  SetName = Olonets Defense
  Apply

SelectRegion = $Donetsk

SelectFaction = $RED
SelectRegion = $Donetsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Donetsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Dnk. Gar. Rgt|2nd Dnk. Gar. Rgt|3rd Dnk. Gar. Rgt
  SetName = 1st Donetsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Dnk. Bty|2nd Dnk. Bty|3rd Dnk. Bty|4th Dnk. Bty
  SetName = Donetsk Defense
  Apply

SelectRegion = $Bobruisk

SelectFaction = $RED
SelectRegion = $Bobruisk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Bobruisk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Bbk. Gar. Rgt|2nd Bbk. Gar. Rgt|3rd Bbk. Gar. Rgt
  SetName = 1st Bobruisk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Bty
  SUFlavorName = 1st Bbk. Bty|2nd Bbk. Bty|3rd Bbk. Bty|4th Bbk. Bty
  SetName = Bobruisk Defense
  Apply

SelectRegion = $Pskov

SelectFaction = $RED
SelectRegion = $Pskov
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Pskov Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Psk. Gar. Rgt|2nd Psk. Gar. Rgt|3rd Psk. Gar. Rgt
  SetName = 1st Pskov Garrison
  Apply

SelectRegion = $Velikiye Luki

SelectFaction = $RED
SelectRegion = $Velikiye Luki
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Velikye Luki Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Vlk. Gar. Rgt|2nd Vlk. Gar. Rgt|3rd Vlk. Gar. Rgt
  SetName = 1st Velikye Luki Garrison
  Apply

SelectRegion = $Polotsk

SelectFaction = $RED
SelectRegion = $Polotsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Polotsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Pol. Gar. Rgt|2nd Pol. Gar. Rgt|3rd Pol. Gar. Rgt
  SetName = 1st Polotsk Garrison
  Apply

SelectRegion = $Vitebsk

SelectFaction = $RED
SelectRegion = $Vitebsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Vitebsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Vit. Gar. Rgt|2nd Vit. Gar. Rgt|3rd Vit. Gar. Rgt
  SetName = 1st Vitebsk Garrison
  Apply

SelectRegion = $Vyazma

SelectFaction = $RED
SelectRegion = $Vyazma
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Vyazma Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Vyz. Gar. Rgt|2nd Vyz. Gar. Rgt|3rd Vyz. Gar. Rgt
  SetName = 1st Vyazma Garrison
  Apply

SelectRegion = $Tver

SelectFaction = $RED
SelectRegion = $Tver
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Tver Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Tck
  SUFlavorName = Tver Cheka
  SetName = Tver Cheka
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Tvr Gar. Rgt|2nd Tvr Gar. Rgt|3rd Tvr Gar. Rgt
  SetName = 1st Tver Garrison
  Apply

SelectRegion = $Podolsk

SelectFaction = $RED
SelectRegion = $Podolsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Podolsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Pod. Gar. Rgt|2nd Pod. Gar. Rgt|3rd Pod. Gar. Rgt
  SetName = 1st Podolsk Garrison
  Apply

SelectRegion = $Rybinsk

SelectFaction = $RED
SelectRegion = $Rybinsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Rybinsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Ryb Gar. Rgt|2nd Ryb Gar. Rgt|3rd Ryb Gar. Rgt
  SetName = 1st Rybinsk Garrison
  Apply

SelectRegion = $Taganrog

SelectFaction = $RED
SelectRegion = $Taganrog
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Taganrog Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Tgr. Gar. Rgt|2nd Tgr. Gar. Rgt|3rd Tgr. Gar. Rgt
  SetName = 1st Taganrog Garrison
  Apply

SelectRegion = $Novocherkassk

SelectFaction = $RED
SelectRegion = $Novocherkassk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Novocherkassk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Nvck. Gar. Rgt|2nd Nvck. Gar. Rgt|3rd Nvck. Gar. Rgt
  SetName = 1st Novocherkassk Garrison
  Apply

SelectRegion = $Tambov

SelectFaction = $RED
SelectRegion = $Tambov
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Tambov Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Tam. Gar. Rgt|2nd Tam. Gar. Rgt|3rd Tam. Gar. Rgt
  SetName = 1st Tambov Garrison
  Apply

SelectRegion = $Penza

SelectFaction = $RED
SelectRegion = $Penza
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Penza Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Pnz. Gar. Rgt|2nd Pnz. Gar. Rgt|3rd Pnz. Gar. Rgt
  SetName = 1st Penza Garrison
  Apply

SelectRegion = $Stavropol

SelectFaction = $RED
SelectRegion = $Stavropol
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Stavropol Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Stv. Gar. Rgt|2nd Stv. Gar. Rgt|3rd Stv. Gar. Rgt
  SetName = 1st Stavropol Garrison
  Apply

SelectRegion = $Simbirsk

SelectFaction = $RED
SelectRegion = $Simbirsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Simbirsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Sim. Gar. Rgt|2nd Sim. Gar. Rgt|3rd Sim. Gar. Rgt
  SetName = 1st Simbirsk Garrison
  Apply

SelectRegion = $Vologda

SelectFaction = $RED
SelectRegion = $Vologda
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Vologda Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Vlg. Gar. Rgt|2nd Vlg. Gar. Rgt|3rd Vlg. Gar. Rgt
  SetName = 1st Vologda Garrison
  Apply

SelectRegion = $Ufa

SelectFaction = $RED
SelectRegion = $Ufa
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Ufa Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Tck
  SUFlavorName = Ufa Cheka
  SetName = Ufa Cheka
  Apply
  CreateUnit
  SetType = $uni_RED_Gar3
  SUFlavorName = 1st Ufa. Gar. Rgt|2nd Ufa. Gar. Rgt|3rd Ufa. Gar. Rgt
  SetName = 1st Ufa Garrison
  Apply
  NULL = NULL

SelectRegion = $Baranavichy

SelectFaction = $RED
SelectRegion = $Baranavichy
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Baranavichy Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Baranavichy Red Guards|2nd Baranavichy Red Guards
  SetName = Baranavichy Red Guards
  Apply

SelectRegion = $Gatchina

SelectFaction = $RED
SelectRegion = $Gatchina
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Gatchina Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Gatchina Red Guards|2nd Gatchina Red Guards
  SetName = Gatchina Red Guards
  Apply

SelectRegion = $Tsarskoye Selo

SelectFaction = $RED
SelectRegion = $Tsarskoye Selo
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Tsarskoye Selo Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Tsarskoye Selo Red Guards|2nd Tsarskoye Selo Red Guards
  SetName = Tsarskoye Selo Red Guards
  Apply

SelectRegion = $Tikhvin

SelectFaction = $RED
SelectRegion = $Tikhvin
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Tikhvin Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Tikhvin Red Guards|2nd Tikhvin Red Guards
  SetName = Tikhvin Red Guards
  Apply

SelectRegion = $Luga

SelectFaction = $RED
SelectRegion = $Luga
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Luga Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Luga Red Guards|2nd Luga Red Guards
  SetName = Luga Red Guards
  Apply

SelectRegion = $Staraya Russa

SelectFaction = $RED
SelectRegion = $Staraya Russa
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Staraya Russa Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Staraya Russa Red Guards|2nd Staraya Russa Red Guards
  SetName = Staraya Russa Red Guards
  Apply

SelectRegion = $Orsha

SelectFaction = $RED
SelectRegion = $Orsha
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Orsha Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Orsha Red Guards|2nd Orsha Red Guards
  SetName = Orsha Red Guards
  Apply

SelectRegion = $Mogilev

SelectFaction = $RED
SelectRegion = $Mogilev
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Mogilev Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Mogilev Red Guards|2nd Mogilev Red Guards
  SetName = Mogilev Red Guards
  Apply

SelectRegion = $Gomel

SelectFaction = $RED
SelectRegion = $Gomel
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Gomel Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Gomel Red Guards|2nd Gomel Red Guards
  SetName = Gomel Red Guards
  Apply

SelectRegion = $Konotop

SelectFaction = $RED
SelectRegion = $Konotop
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Konotop Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Konotop Red Guards|2nd Konotop Red Guards
  SetName = Konotop Red Guards
  Apply

SelectRegion = $Rzhev

SelectFaction = $RED
SelectRegion = $Rzhev
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Rzhev Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Rzhev Red Guards|2nd Rzhev Red Guards
  SetName = Rzhev Red Guards
  Apply

SelectRegion = $Kolomna

SelectFaction = $RED
SelectRegion = $Kolomna
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Kolomna Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Kolomna Red Guards|2nd Kolomna Red Guards
  SetName = Kolomna Red Guards
  Apply

SelectRegion = $Sergiev Posad

SelectFaction = $RED
SelectRegion = $Sergiev Posad
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Sergiev Posad Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Sergiev Posad Red Guards|2nd Sergiev Posad Red Guards
  SetName = Sergiev Posad Red Guards
  Apply

SelectRegion = $Bogodorosk

SelectFaction = $RED
SelectRegion = $Bogodorosk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Bogodorosk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Bogodorosk Red Guards|2nd Bogodorosk Red Guards
  SetName = Bogodorosk Red Guards
  Apply

SelectRegion = $Cherepovets

SelectFaction = $RED
SelectRegion = $Cherepovets
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Tcherepovets Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Tcherepovets Red Guards|2nd Tcherepovets Red Guards
  SetName = Tcherepovets Red Guards
  Apply

SelectRegion = $Kostroma

SelectFaction = $RED
SelectRegion = $Kostroma
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Kostroma Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Kostroma Red Guards|2nd Kostroma Red Guards
  SetName = Kostroma Red Guards
  Apply

SelectRegion = $Serpukhov

SelectFaction = $RED
SelectRegion = $Serpukhov
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Serpukhov Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Serpukhov Red Guards|2nd Serpukhov Red Guards
  SetName = Serpukhov Red Guards
  Apply

SelectRegion = $Staryy Oskol

SelectFaction = $RED
SelectRegion = $Staryy Oskol
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Staryy Oskol Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Staryy Oskol Red Guards|2nd Staryy Oskol Red Guards
  SetName = Staryy Oskol Red Guards
  Apply

SelectRegion = $Zadonsk

SelectFaction = $RED
SelectRegion = $Zadonsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Zadonsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Zadonsk Red Guards|2nd Zadonsk Red Guards
  SetName = Zadonsk Red Guards
  Apply

SelectRegion = $Pavlovsk

SelectFaction = $RED
SelectRegion = $Pavlovsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Pavlovsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Pavlovsk Red Guards|2nd Pavlovsk Red Guards
  SetName = Pavlovsk Red Guards
  Apply

SelectRegion = $Murom

SelectFaction = $RED
SelectRegion = $Murom
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Murom Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Murom Red Guards|2nd Murom Red Guards
  SetName = Murom Red Guards
  Apply

SelectRegion = $Arzamas

SelectFaction = $RED
SelectRegion = $Arzamas
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Arzamas Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Arzamas Red Guards|2nd Arzamas Red Guards
  SetName = Arzamas Red Guards
  Apply

SelectRegion = $Cheboksary

SelectFaction = $RED
SelectRegion = $Cheboksary
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Cheboksary Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Cheboksary Red Guards|2nd Cheboksary Red Guards
  SetName = Cheboksary Red Guards
  Apply

SelectRegion = $Ryazhsk

SelectFaction = $RED
SelectRegion = $Ryazhsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Ryazhsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Ryazhsk Red Guards|2nd Ryazhsk Red Guards
  SetName = Ryazhsk Red Guards
  Apply

SelectRegion = $Lipetsk

SelectFaction = $RED
SelectRegion = $Lipetsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Lipetsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Lipetsk Red Guards|2nd Lipetsk Red Guards
  SetName = Lipetsk Red Guards
  Apply

SelectRegion = $Kozlov

SelectFaction = $RED
SelectRegion = $Kozlov
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Kozlov Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Kozlov Red Guards|2nd Kozlov Red Guards
  SetName = Kozlov Red Guards
  Apply

SelectRegion = $Morshansk

SelectFaction = $RED
SelectRegion = $Morshansk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Morshansk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Morshansk Red Guards|2nd Morshansk Red Guards
  SetName = Morshansk Red Guards
  Apply

SelectRegion = $Liski

SelectFaction = $RED
SelectRegion = $Liski
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Liski Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Liski Red Guards|2nd Liski Red Guards
  SetName = Liski Red Guards
  Apply

SelectRegion = $Saransk

SelectFaction = $RED
SelectRegion = $Saransk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Saransk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Saransk Red Guards|2nd Saransk Red Guards
  SetName = Saransk Red Guards
  Apply

SelectRegion = $Kuznetsk

SelectFaction = $RED
SelectRegion = $Kuznetsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Kuznetsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Kuznetsk Red Guards|2nd Kuznetsk Red Guards
  SetName = Kuznetsk Red Guards
  Apply

SelectRegion = $Pokrovsk

SelectFaction = $RED
SelectRegion = $Pokrovsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Pokrovsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Pokrovsk Red Guards|2nd Pokrovsk Red Guards
  SetName = Pokrovsk Red Guards
  Apply

SelectRegion = $Balashov

SelectFaction = $RED
SelectRegion = $Balashov
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Balashov Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Balashov Red Guards|2nd Balashov Red Guards
  SetName = Balashov Red Guards
  Apply

SelectRegion = $Mikhailovka

SelectFaction = $RED
SelectRegion = $Mikhailovka
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Mikhailovka Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Mikhailovka Red Guards|2nd Mikhailovka Red Guards
  SetName = Mikhailovka Red Guards
  Apply

SelectRegion = $Kamyshin

SelectFaction = $RED
SelectRegion = $Kamyshin
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Kamyshin Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Kamyshin Red Guards|2nd Kamyshin Red Guards
  SetName = Kamyshin Red Guards
  Apply

SelectRegion = $Elista

SelectFaction = $RED
SelectRegion = $Elista
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Elista Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Elista Red Guards|2nd Elista Red Guards
  SetName = Elista Red Guards
  Apply

SelectRegion = $Bataisk

SelectFaction = $RED
SelectRegion = $Bataisk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Bataisk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Bataisk Red Guards|2nd Bataisk Red Guards
  SetName = Bataisk Red Guards
  Apply

SelectRegion = $Azov

SelectFaction = $RED
SelectRegion = $Azov
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Azov Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Azov Red Guards|2nd Azov Red Guards
  SetName = Azov Red Guards
  Apply

SelectRegion = $Salsk

SelectFaction = $RED
SelectRegion = $Salsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Salsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Salsk Red Guards|2nd Salsk Red Guards
  SetName = Salsk Red Guards
  Apply

SelectRegion = $Grozny

SelectFaction = $RED
SelectRegion = $Grozny
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Grozny Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Grozny Red Guards|2nd Grozny Red Guards
  SetName = Grozny Red Guards
  Apply

SelectRegion = $Petrovsk-Port

SelectFaction = $RED
SelectRegion = $Petrovsk-Port
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Petrovsk-Port Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Petrovsk-Port Red Guards|2nd Petrovsk-Port Red Guards
  SetName = Petrovsk-Port Red Guards
  Apply

SelectRegion = $Volsk

SelectFaction = $RED
SelectRegion = $Volsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Volsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Volsk Red Guards|2nd Volsk Red Guards
  SetName = Volsk Red Guards
  Apply

SelectRegion = $Volzhskiy

SelectFaction = $RED
SelectRegion = $Volzhskiy
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Volzhskiy Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Volzhskiy Red Guards|2nd Volzhskiy Red Guards
  SetName = Volzhskiy Red Guards
  Apply

SelectRegion = $Derbent

SelectFaction = $RED
SelectRegion = $Derbent
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Derbent Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Derbent Red Guards|2nd Derbent Red Guards
  SetName = Derbent Red Guards
  Apply

SelectRegion = $Petrozavodsk

SelectFaction = $RED
SelectRegion = $Petrozavodsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Petrozavodsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Petrozavodsk Red Guards|2nd Petrozavodsk Red Guards
  SetName = Petrozavodsk Red Guards
  Apply

SelectRegion = $Medvezhya Gora

SelectFaction = $RED
SelectRegion = $Medvezhya Gora
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Medvezhya Gora Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Medvezhya Gora Red Guards|2nd Medvezhya Gora Red Guards
  SetName = Medvezhya Gora Red Guards
  Apply

SelectRegion = $Segezha

SelectFaction = $RED
SelectRegion = $Segezha
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Segezha Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Segezha Red Guards|2nd Segezha Red Guards
  SetName = Segezha Red Guards
  Apply

SelectRegion = $Onega

SelectFaction = $RED
SelectRegion = $Onega
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Onega Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Onega Red Guards|2nd Onega Red Guards
  SetName = Onega Red Guards
  Apply

SelectRegion = $Letniy Bereg

SelectFaction = $RED
SelectRegion = $Letniy Bereg
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Letniy Bereg Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Letniy Bereg Red Guards|2nd Letniy Bereg Red Guards
  SetName = Letniy Bereg Red Guards
  Apply

SelectRegion = $Vytegra

SelectFaction = $RED
SelectRegion = $Vytegra
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Vytegra Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Vytegra Red Guards|2nd Vytegra Red Guards
  SetName = Vytegra Red Guards
  Apply

SelectRegion = $Nyandoma

SelectFaction = $RED
SelectRegion = $Nyandoma
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Nyandoma Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Nyandoma Red Guards|2nd Nyandoma Red Guards
  SetName = Nyandoma Red Guards
  Apply

SelectRegion = $Konocha

SelectFaction = $RED
SelectRegion = $Konocha
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Konocha Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Konocha Red Guards|2nd Konocha Red Guards
  SetName = Konocha Red Guards
  Apply

SelectRegion = $Stavropol-on-Volga

SelectFaction = $RED
SelectRegion = $Stavropol-on-Volga
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Stavropol-on-Volga Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Stavropol-on-Volga Red Guards|2nd Stavropol-on-Volga Red Guards
  SetName = Stavropol-on-Volga Red Guards
  Apply

SelectRegion = $Syzran

SelectFaction = $RED
SelectRegion = $Syzran
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Syzran Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Syzran Red Guards|2nd Syzran Red Guards
  SetName = Syzran Red Guards
  Apply

SelectRegion = $Uralsk

SelectFaction = $RED
SelectRegion = $Uralsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Uralsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Uralsk Red Guards|2nd Uralsk Red Guards
  SetName = Uralsk Red Guards
  Apply

SelectRegion = $Balakovo

SelectFaction = $RED
SelectRegion = $Balakovo
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Balakovo Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Balakovo Red Guards|2nd Balakovo Red Guards
  SetName = Balakovo Red Guards
  Apply

SelectRegion = $Gurjev

SelectFaction = $RED
SelectRegion = $Gurjev
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Gurjev Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Gurjev Red Guards|2nd Gurjev Red Guards
  SetName = Gurjev Red Guards
  Apply

SelectRegion = $Sarapul

SelectFaction = $RED
SelectRegion = $Sarapul
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Sarapul Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Sarapul Red Guards|2nd Sarapul Red Guards
  SetName = Sarapul Red Guards
  Apply

SelectRegion = $Izhevsk

SelectFaction = $RED
SelectRegion = $Izhevsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Izhevsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Izhevsk Red Guards|2nd Izhevsk Red Guards
  SetName = Izhevsk Red Guards
  Apply

SelectRegion = $Birsk

SelectFaction = $RED
SelectRegion = $Birsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Birsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Birsk Red Guards|2nd Birsk Red Guards
  SetName = Birsk Red Guards
  Apply

SelectRegion = $Bugulma

SelectFaction = $RED
SelectRegion = $Bugulma
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Bugulma Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Bugulma Red Guards|2nd Bugulma Red Guards
  SetName = Bugulma Red Guards
  Apply

SelectRegion = $Buguruslan

SelectFaction = $RED
SelectRegion = $Buguruslan
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Buguruslan Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Buguruslan Red Guards|2nd Buguruslan Red Guards
  SetName = Buguruslan Red Guards
  Apply

SelectRegion = $Sterlitamak

SelectFaction = $RED
SelectRegion = $Sterlitamak
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Sterlitamak Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Sterlitamak Red Guards|2nd Sterlitamak Red Guards
  SetName = Sterlitamak Red Guards
  Apply

SelectRegion = $Salavat

SelectFaction = $RED
SelectRegion = $Salavat
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Salavat Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Salavat Red Guards|2nd Salavat Red Guards
  SetName = Salavat Red Guards
  Apply

SelectRegion = $Iletsk

SelectFaction = $RED
SelectRegion = $Iletsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Iletsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Iletsk Red Guards|2nd Iletsk Red Guards
  SetName = Iletsk Red Guards
  Apply

SelectRegion = $Aktjubinsk

SelectFaction = $RED
SelectRegion = $Aktjubinsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Aktjubinsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Aktjubinsk Red Guards|2nd Aktjubinsk Red Guards
  SetName = Aktjubinsk Red Guards
  Apply

SelectRegion = $Orsk

SelectFaction = $RED
SelectRegion = $Orsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Orsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Orsk Red Guards|2nd Orsk Red Guards
  SetName = Orsk Red Guards
  Apply

SelectRegion = $Nizhny Tagil

SelectFaction = $RED
SelectRegion = $Nizhny Tagil
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Nizhny Tagil Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Nizhny Tagil Red Guards|2nd Nizhny Tagil Red Guards
  SetName = Nizhny Tagil Red Guards
  Apply

SelectRegion = $Zlatoust

SelectFaction = $RED
SelectRegion = $Zlatoust
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Zlatoust Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Zlatoust Red Guards|2nd Zlatoust Red Guards
  SetName = Zlatoust Red Guards
  Apply

SelectRegion = $Chelyabinsk

SelectFaction = $RED
SelectRegion = $Chelyabinsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Chelyabinsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Chelyabinsk Red Guards|2nd Chelyabinsk Red Guards
  SetName = Chelyabinsk Red Guards
  Apply

SelectRegion = $Shadrinsk

SelectFaction = $RED
SelectRegion = $Shadrinsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Shadrinsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Shadrinsk Red Guards|2nd Shadrinsk Red Guards
  SetName = Shadrinsk Red Guards
  Apply

SelectRegion = $Kustanay

SelectFaction = $RED
SelectRegion = $Kustanay
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Kustanay Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Kustanay Red Guards|2nd Kustanay Red Guards
  SetName = Kustanay Red Guards
  Apply

SelectRegion = $Irbit

SelectFaction = $RED
SelectRegion = $Irbit
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Irbit Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Irbit Red Guards|2nd Irbit Red Guards
  SetName = Irbit Red Guards
  Apply

SelectRegion = $Velsk

SelectFaction = $RED
SelectRegion = $Velsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Velsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Velsk Red Guards|2nd Velsk Red Guards
  SetName = Velsk Red Guards
  Apply

SelectRegion = $Kotlas

SelectFaction = $RED
SelectRegion = $Kotlas
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Kotlas Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Kotlas Red Guards|2nd Kotlas Red Guards
  SetName = Kotlas Red Guards
  Apply

SelectRegion = $Velikiy Ustyug

SelectFaction = $RED
SelectRegion = $Velikiy Ustyug
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Velikiy Ustyug Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Velikiy Ustyug Red Guards|2nd Velikiy Ustyug Red Guards
  SetName = Velikiy Ustyug Red Guards
  Apply

SelectRegion = $Viatka

SelectFaction = $RED
SelectRegion = $Viatka
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Viatka Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Viatka Red Guards|2nd Viatka Red Guards
  SetName = Viatka Red Guards
  Apply

SelectRegion = $Glazov

SelectFaction = $RED
SelectRegion = $Glazov
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Glazov Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Glazov Red Guards|2nd Glazov Red Guards
  SetName = Glazov Red Guards
  Apply

SelectRegion = $Syktyvkar

SelectFaction = $RED
SelectRegion = $Syktyvkar
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Syktyvkar Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Syktyvkar Red Guards|2nd Syktyvkar Red Guards
  SetName = Syktyvkar Red Guards
  Apply

SelectRegion = $Nadejdinsk

SelectFaction = $RED
SelectRegion = $Nadejdinsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Nadejdinsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Nadejdinsk Red Guards|2nd Nadejdinsk Red Guards
  SetName = Nadejdinsk Red Guards
  Apply

SelectRegion = $Aralsk

SelectFaction = $RED
SelectRegion = $Aralsk
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Aralsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Aralsk Red Guards|2nd Aralsk Red Guards
  SetName = Aralsk Red Guards
  Apply

SelectRegion = $Tikhoretskaya

SelectFaction = $RED
SelectRegion = $Tikhoretskaya
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Tikhoretsk Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Tikhoretsk Red Guards|2nd Tikhoretsk Red Guards
  SetName = Tikhoretsk Red Guards
  Apply

SelectRegion = $Kinechma

SelectFaction = $RED
SelectRegion = $Kinechma
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Kinechma Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Kinechma Red Guards|2nd Kinechma Red Guards
  SetName = Kinechma Red Guards
  Apply

SelectRegion = $Kizlyar

SelectFaction = $RED
SelectRegion = $Kizlyar
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Kizlyar Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Kizlyar Red Guards|2nd Kizlyar Red Guards
  SetName = Kizlyar Red Guards
  Apply

SelectRegion = $Kotelnich

SelectFaction = $RED
SelectRegion = $Kotelnich
  CreateGroup
  Posture = $Defensive
  SetKind = $Land
  Entranch = 2
  InCS = 1
  FixType = 999
  SetName = Kotelnich Garrison
  Apply
  CreateUnit
  SetType = $uni_RED_Mil3
  SUFlavorName = 1st Kotelnich Red Guards|2nd Kotelnich Red Guards
  SetName = Kotelnich Red Guards
  Apply
